### ISSUE TITLE
How to start in full screen mode?

### ISSUE THREAD

**Issue by And329** [coderedart/egui_overlay#34]
Hi, was trying to figure out how to start the app in fullscreen (for basic example)

**Comment by coderedart** [comment]
I would not recommend using fullscreen mode because it causes issues with transparency. On windows, you will just find a black window if your window is fullscreen or if the window size is the same of the monitor. 

As a hack, I recommend getting the monitor "size", and setting your window to `monitor_width - 1, monitor_height - 1` size.
To get monitor size, you can use https://docs.rs/glfw-passthrough/latest/glfw_passthrough/struct.Glfw.html#method.with_primary_monitor

If you really want to use fullscreen, then just get the monitor with the above linked method and set fullscreen mode of the window with https://docs.rs/glfw-passthrough/latest/glfw_passthrough/struct.Window.html#method.set_monitor 
There's a simple example at https://github.com/coderedart/glfw-rs-passthrough/blob/master/examples/fullscreen.rs#L68

OTOH, you can also just do `window.maximize()` which would be practically fullscreen (ignoring taskbar or other elements) as there's no borders for the window.

**Comment by coderedart** [comment]
You can also ask the questions in https://github.com/coderedart/egui_overlay/discussions

**Comment by And329** [comment]
thx)
