### ISSUE TITLE
Cursor cannot interact with controls directly on Retina Display (Mac OS)

### ISSUE THREAD

**Issue by mchaliadzinau** [coderedart/egui_overlay#9]
On Retina display I have issues when interacting with controls (they are rendered on one place but in order to interact them, cursor should be in other place).

https://github.com/coderedart/egui_overlay/assets/32924456/1cbe949e-4845-4d1a-b7d5-1539e088f557

It works OK on external monitor (LG), but has aforementioned issue when window is on Retina display (even with detached external monitor).

Monitors: 
- Built-in: Retina XDR Display 14-inch (3024 × 1964)
- External: LG 34,5-inch (2560 × 1080)

Logs when I start example on Retina Display:
```
2023-07-01T13:23:30.270803Z DEBUG egui_render_wgpu: using wgpu backends: Backends(VULKAN | GL | METAL | DX12 | DX11 | BROWSER_WEBGPU)
2023-07-01T13:23:30.271684Z DEBUG egui_render_wgpu: iterating over all adapters
2023-07-01T13:23:30.276749Z DEBUG egui_render_wgpu: adapter: AdapterInfo {
    name: "Apple M2 Pro",
    vendor: 0,
    device: 0,
    device_type: IntegratedGpu,
    driver: "",
    driver_info: "",
    backend: Metal,
}
2023-07-01T13:23:30.276929Z DEBUG egui_render_wgpu: creating a surface with AppKit(AppKitWindowHandle { ns_window: 0x1502753c0, ns_view: 0x1502b8710 })
2023-07-01T13:23:30.277751Z  INFO egui_render_wgpu: is surfaced created at startup?: true
2023-07-01T13:23:30.277766Z DEBUG egui_render_wgpu: using power preference: LowPower
2023-07-01T13:23:30.277956Z  INFO egui_render_wgpu: chosen adapter details: AdapterInfo { name: "Apple M2 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-07-01T13:23:30.280114Z DEBUG egui_render_wgpu: supported alpha modes: [
    Opaque,
    PostMultiplied,
]
2023-07-01T13:23:30.280128Z DEBUG egui_render_wgpu: supported formats of the surface: [
    Bgra8UnormSrgb,
    Bgra8Unorm,
    Rgba16Float,
    Rgb10a2Unorm,
]
2023-07-01T13:23:30.280136Z DEBUG egui_render_wgpu: using format: Bgra8UnormSrgb for surface configuration
2023-07-01T13:23:30.280143Z  INFO egui_render_wgpu: reconfiguring surface with config: SurfaceConfiguration {
    usage: TextureUsages(
        RENDER_ATTACHMENT,
    ),
    format: Bgra8UnormSrgb,
    width: 1600,
    height: 1200,
    present_mode: Fifo,
    alpha_mode: PostMultiplied,
    view_formats: [
        Bgra8UnormSrgb,
    ],
}
2023-07-01T13:23:30.280270Z DEBUG egui_render_wgpu: device features: Features(
    0x0,
)
2023-07-01T13:23:30.280278Z DEBUG egui_render_wgpu: device limits: Limits {
    max_texture_dimension_1d: 2048,
    max_texture_dimension_2d: 2048,
    max_texture_dimension_3d: 256,
    max_texture_array_layers: 256,
    max_bind_groups: 4,
    max_bindings_per_bind_group: 640,
    max_dynamic_uniform_buffers_per_pipeline_layout: 8,
    max_dynamic_storage_buffers_per_pipeline_layout: 0,
    max_sampled_textures_per_shader_stage: 16,
    max_samplers_per_shader_stage: 16,
    max_storage_buffers_per_shader_stage: 0,
    max_storage_textures_per_shader_stage: 0,
    max_uniform_buffers_per_shader_stage: 11,
    max_uniform_buffer_binding_size: 16384,
    max_storage_buffer_binding_size: 0,
    max_vertex_buffers: 8,
    max_buffer_size: 268435456,
    max_vertex_attributes: 16,
    max_vertex_buffer_array_stride: 255,
    min_uniform_buffer_offset_alignment: 256,
    min_storage_buffer_offset_alignment: 256,
    max_inter_stage_shader_components: 60,
    max_compute_workgroup_storage_size: 0,
    max_compute_invocations_per_workgroup: 0,
    max_compute_workgroup_size_x: 0,
    max_compute_workgroup_size_y: 0,
    max_compute_workgroup_size_z: 0,
    max_compute_workgroups_per_dimension: 0,
    max_push_constant_size: 0,
}
2023-07-01T13:23:30.286536Z  INFO egui_window_glfw_passthrough: entering glfw event loop
2023-07-01T13:23:30.357082Z  INFO egui_render_wgpu: reconfiguring surface with config: SurfaceConfiguration {
    usage: TextureUsages(
        RENDER_ATTACHMENT,
    ),
    format: Bgra8UnormSrgb,
    width: 1600,
    height: 1200,
    present_mode: Fifo,
    alpha_mode: PostMultiplied,
    view_formats: [
        Bgra8UnormSrgb,
    ],
}
```

Logs when I start example on LG Display (works almost fine, the only small issue is that window header seems a bit off, only lover part is clickable (you can see this on next video after logs)):
```
2023-07-01T13:22:44.957585Z DEBUG egui_render_wgpu: using wgpu backends: Backends(VULKAN | GL | METAL | DX12 | DX11 | BROWSER_WEBGPU)
2023-07-01T13:22:44.958416Z DEBUG egui_render_wgpu: iterating over all adapters
2023-07-01T13:22:44.963285Z DEBUG egui_render_wgpu: adapter: AdapterInfo {
    name: "Apple M2 Pro",
    vendor: 0,
    device: 0,
    device_type: IntegratedGpu,
    driver: "",
    driver_info: "",
    backend: Metal,
}
2023-07-01T13:22:44.963455Z DEBUG egui_render_wgpu: creating a surface with AppKit(AppKitWindowHandle { ns_window: 0x13782bda0, ns_view: 0x14778c3d0 })
2023-07-01T13:22:44.964181Z  INFO egui_render_wgpu: is surfaced created at startup?: true
2023-07-01T13:22:44.964194Z DEBUG egui_render_wgpu: using power preference: LowPower
2023-07-01T13:22:44.964363Z  INFO egui_render_wgpu: chosen adapter details: AdapterInfo { name: "Apple M2 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-07-01T13:22:44.966233Z DEBUG egui_render_wgpu: supported alpha modes: [
    Opaque,
    PostMultiplied,
]
2023-07-01T13:22:44.966248Z DEBUG egui_render_wgpu: supported formats of the surface: [
    Bgra8UnormSrgb,
    Bgra8Unorm,
    Rgba16Float,
    Rgb10a2Unorm,
]
2023-07-01T13:22:44.966256Z DEBUG egui_render_wgpu: using format: Bgra8UnormSrgb for surface configuration
2023-07-01T13:22:44.966263Z  INFO egui_render_wgpu: reconfiguring surface with config: SurfaceConfiguration {
    usage: TextureUsages(
        RENDER_ATTACHMENT,
    ),
    format: Bgra8UnormSrgb,
    width: 800,
    height: 600,
    present_mode: Fifo,
    alpha_mode: PostMultiplied,
    view_formats: [
        Bgra8UnormSrgb,
    ],
}
2023-07-01T13:22:44.966389Z DEBUG egui_render_wgpu: device features: Features(
    0x0,
)
2023-07-01T13:22:44.966396Z DEBUG egui_render_wgpu: device limits: Limits {
    max_texture_dimension_1d: 2048,
    max_texture_dimension_2d: 2048,
    max_texture_dimension_3d: 256,
    max_texture_array_layers: 256,
    max_bind_groups: 4,
    max_bindings_per_bind_group: 640,
    max_dynamic_uniform_buffers_per_pipeline_layout: 8,
    max_dynamic_storage_buffers_per_pipeline_layout: 0,
    max_sampled_textures_per_shader_stage: 16,
    max_samplers_per_shader_stage: 16,
    max_storage_buffers_per_shader_stage: 0,
    max_storage_textures_per_shader_stage: 0,
    max_uniform_buffers_per_shader_stage: 11,
    max_uniform_buffer_binding_size: 16384,
    max_storage_buffer_binding_size: 0,
    max_vertex_buffers: 8,
    max_buffer_size: 268435456,
    max_vertex_attributes: 16,
    max_vertex_buffer_array_stride: 255,
    min_uniform_buffer_offset_alignment: 256,
    min_storage_buffer_offset_alignment: 256,
    max_inter_stage_shader_components: 60,
    max_compute_workgroup_storage_size: 0,
    max_compute_invocations_per_workgroup: 0,
    max_compute_workgroup_size_x: 0,
    max_compute_workgroup_size_y: 0,
    max_compute_workgroup_size_z: 0,
    max_compute_workgroups_per_dimension: 0,
    max_push_constant_size: 0,
}
2023-07-01T13:22:44.972230Z  INFO egui_window_glfw_passthrough: entering glfw event loop
2023-07-01T13:22:45.022468Z  INFO egui_window_glfw_passthrough: framebuffer size changed to 1600,1200
2023-07-01T13:22:45.022491Z  INFO egui_window_glfw_passthrough: framebuffer size changed to 800,600
2023-07-01T13:22:45.022505Z  INFO egui_render_wgpu: reconfiguring surface with config: SurfaceConfiguration {
    usage: TextureUsages(
        RENDER_ATTACHMENT,
    ),
    format: Bgra8UnormSrgb,
    width: 800,
    height: 600,
    present_mode: Fifo,
    alpha_mode: PostMultiplied,
    view_formats: [
        Bgra8UnormSrgb,
    ],
}
```

Attaching video where I move overlay from LG monitor to Built-in Retina display:
https://github.com/coderedart/egui_overlay/assets/32924456/2af89a2c-5048-4105-ba6d-94801a1c548e

**Comment by coderedart** [comment]
oof, that took a long time to figure out. I **think** i might have fixed it. you can try running the basic example with the latest commit and latest versions of glfw (0.4.2)/wgpu (0.4.3) backends. @mchaliadzinau 

If the issue is not fixed, try moving the window between monitors and post the values of `scale`, `pixels_per_virtual_unit` and window width/height in the ui as well as the width/height in the logs. How they change could be a clue to debug this issue.

The problem arises from a weird interaction between these three different units and how to translate between them on hidpi/normal monitors.

**Comment by mchaliadzinau** [comment]
The issue is fixed! Great job @coderedart and thank you for addressing it!

Everything works correctly regardless where I start the app or move the window. The cursor position in bottom right corner always equals to width/height shown in the ui.
Inc/dec works w/o issue as well

The only small issue left is 
> that window header seems a bit off, only lover part is clickable (you can see this on next video)
> https://github.com/coderedart/egui_overlay/assets/32924456/2af89a2c-5048-4105-ba6d-94801a1c548e

I'm not sure if this related issue or not.

**Comment by coderedart** [comment]
> that window header seems a bit off, only lover part is clickable (you can see this on next video)

That is beyond me at the moment. I tried peeking into glfw code, but it simply sets the https://developer.apple.com/documentation/appkit/nswindow/1419354-ignoresmouseevents flag to true and nothing else. As we are dealing with rust code -> C glfw code -> objective C stuff, i am afraid of even attempting to unravel this mess xD. I tried googling, but couldn't find anything. Not surprising because this is such a niche topic.

I recommend just living with this bug for now. 

But, anyway, good to know that this is finally working. Thanks for all the help with debugging. Feel free to close the issue :) 


I will write down the solution here just in case i forget about this in future.

https://www.glfw.org/docs/3.3/intro_guide.html#coordinate_systems 
So, there are three different units used when referring to size/position.

1. physical pixels. This represents raw physical pixels of the framebuffer/screen/monitor.
2. virtual screen coordinates (units). These may or may not be the same size as the pixels. But these are the units used to give you window position/size relative to the monitor.
3. logical points. These are what egui usually deals with. the number of pixels per logical point is called "content scale".

Almost all sizes glfw gives us are in virtual units except monitor size (millimeters) and framebuffer size (physical pixels). Glfw also allows us to query “Content scale”. This is a `float` set by user to tell us how much we should be scaling our UI. In simple terms, if we use a scale of 1.0 on a 1080p monitor of 22 inches, a character might take 20 pixels. But on a 1080p phone screen of 6 inches, the user won’t be able to read a character of 20 pixels size. So, usually, the content scale will be around 3.0-4.0. This makes the character take 60-80 pixels, and be a readable size on the tiny hidpi phone screen. So, you could say your character takes "20" logical points. And the content scale will decide, how many raw pixels we use. 

egui deals with units based on the winit system of physical/logical units. winit uses physical pixels. And it uses content scale, to define “logical points”. So, on a screen with a scale of 2.0, logical points are made up of 2 pixels per point. that is why, egui calls it “pixels_per_point” in RawInput struct. This makes it easy for egui to integrate with winit.

The problem? Glfw’s virtual units don’t necessarily map to logical points. On some displays, the virtual units could be same as physical pixel units. It is the responsibility of user to divide virtual units with physical pixels and figure out the number of pixels per virtual unit. And keep this separate from the content scale. glfw will give us window pos/size, cursor pos etc.. in virtual units. We should multiply them with the number of pixels per virtual unit, to convert them into units of physical pixels. Now, we divide by content scale, to convert them into logical points. 

So, we will “emulate” logical points to match the egui (winit) style of units.

I probably emscripten support with 0.4.2 release. But, fixing it involves another unit called CSS points :sob: .

**Comment by coderedart** [comment]
0.4.1 `egui_overlay` released with Mac support :+1:

**Comment by mchaliadzinau** [comment]
Great job @coderedart and thank you for the effort to fix the issues!

> > that window header seems a bit off, only lover part is clickable (you can see this on next video)
>
>That is beyond me at the moment. I tried peeking into glfw code, but it simply sets the https://developer.apple.com/documentation/appkit/nswindow/1419354-ignoresmouseevents flag to true and nothing else. As we are dealing with rust code -> C glfw code -> objective C stuff, i am afraid of even attempting to unravel this mess xD. I tried googling, but couldn't find anything. Not surprising because this is such a niche topic.
>
> I recommend just living with this bug for now.

I understand, besides this should not be an issue for most cases (Why would anyone want window header visible for overlay? ). 
But everything is possible since use cases are endless, may be it is better to mention this as known-issue in Readme?
